#!/usr/bin/perl -w
# -*-cperl-*-

# $Id$
# $URL$

use strict;

my $ORIG_CONFIG = "aproot/conf/original/httpd.conf";
my $CONFIG = "aproot/conf/httpd.conf";
my $NEWCONFIG = "aproot/conf/httpd.conf.new";
my $LIMESTONE_CONFIG = "aproot/conf/limestone.conf";

my $WD = `pwd`;
chomp $WD;
my $TMPDIR = "${WD}/tmp";
my $FILEDIR = "${WD}/files";

my ($CONF_PGSQL_VHOST, $CONF_MYSQL_VHOST) = ("no", "no");

-d $TMPDIR or mkdir($TMPDIR) or die ("couldn't make $TMPDIR");
-d $FILEDIR or mkdir($FILEDIR) or die ("couldn't make $FILEDIR");
 

sub print_dav_vhost_config ($$$$$$$$$) {
  my ($config_fh, $vhost_port, $db_driver, $db_host, $db_port, $db_sock, $db_name, $db_user, $db_pass) = (shift, shift, shift, shift, shift, shift, shift, shift, shift);

  my $ROOT_PATH = "/";

  my $host_domain = $ENV{'LIMESTONE_HOST_DOMAIN'};
  my $port_part_of_host;
  if ($vhost_port) {
    $port_part_of_host = ":${vhost_port}";
  } else {
    $port_part_of_host = "";
    $vhost_port = 80;
  }


  print $config_fh qq/DBDriver $db_driver\n/;
  if ($db_driver eq "pgsql") {
    print $config_fh qq/DBDParams "host=$db_host /;
    print $config_fh qq/port=$db_port / if $db_port;
    print $config_fh qq/dbname=$db_name user=$db_user password=$db_pass"\n/;
  } elsif ($db_driver eq "mysql") {
    print $config_fh qq/  DBDParams "/;
    if ($db_sock) {
      print $config_fh "sock=$db_sock ";
    } else {
      print $config_fh "host=$db_host ";
      print $config_fh "port=$db_port " if $db_port;
    }
    print $config_fh qq/dbname=$db_name user=$db_user pass=$db_pass"\n/;
  }
  ;

  print $config_fh <<EOF
DAVLimestoneIndexCSS  http://$host_domain${port_part_of_host}/css/style.css
DAVDBMSTmpDir $TMPDIR
DAVDBMSFileDir $FILEDIR
# To allow depth: infinity PROPFINDs required by some clients.
DAVDepthInfinity on
SetInputFilter hammock-filter

<Location ${ROOT_PATH}>
  DAV repos
  ModMimeUsePathInfo on

  DAVUnauthenticatedAccess on
    DAVResponseRewriteCond Host                 ^(drive\\.)?[^.]+.$host_domain.*
    DAVResponseRewriteRule /home/[^/]*/?(.*)   /\$1

  AuthType Digest
  AuthName "users\@limebits.com"
  BrowserMatch ".*MSIE.*" AuthDigestEnableQueryStringHack=On

  AuthDigestProvider dbd

  Require valid-user

  #SQL query to verify a user
  #(note: DBD drivers recognise both stdio-like %s and native syntax)
  #Digest Authentication with mod_authn_dbd *requires* the query to have 2 parameters - user and realm.
  #We dont store the realm in database, hence the useless construct ' name != %s ' to dummify realm !
   AuthDBDUserRealmQuery "SELECT pwhash FROM principals INNER JOIN users ON principals.resource_id = users.principal_id WHERE name = %s and name != %s"

</Location>

NameVirtualHost *:${vhost_port}
Listen $vhost_port

<VirtualHost *:${vhost_port}>
  ServerName ${host_domain}:${vhost_port}

</VirtualHost>
EOF
;
}

my ($sql1, $sql2) = (shift, shift);
$CONF_PGSQL_VHOST="yes" if ($sql1 && ($sql1 eq "pgsql") || $sql2 && ($sql2 eq "pgsql"));
$CONF_MYSQL_VHOST="yes" if ($sql1 && ($sql1 eq "mysql") || $sql2 && ($sql2 eq "mysql"));

open(LIMESTONE_CONFIG, '>', $LIMESTONE_CONFIG) or die("couldn't open $LIMESTONE_CONFIG");

if ($CONF_PGSQL_VHOST eq "yes") {
  my $LSPORT = $ENV{'LIMESTONE_PGSQL_VHOST_PORT'};
  my $DBHOST = $ENV{'LIMESTONE_PGSQL_DB_HOST'};
  my $DBPORT = $ENV{'LIMESTONE_PGSQL_DB_PORT'};
  my $DBNAME = $ENV{'LIMESTONE_PGSQL_DB_NAME'};
  my $DBUSER = $ENV{'LIMESTONE_PGSQL_DB_USER'};
  my $DBPASS = $ENV{'LIMESTONE_PGSQL_DB_PASS'};
  print_dav_vhost_config
    (*LIMESTONE_CONFIG, $LSPORT, "pgsql", $DBHOST, $DBPORT, 0, $DBNAME, $DBUSER, $DBPASS)
}

if ($CONF_MYSQL_VHOST eq "yes") {
  my $LSPORT = $ENV{'LIMESTONE_MYSQL_VHOST_PORT'};
  my $DBHOST = $ENV{'LIMESTONE_MYSQL_DB_HOST'};
  my $DBPORT = $ENV{'LIMESTONE_MYSQL_DB_PORT'};
  my $DBSOCK = $ENV{'LIMESTONE_MYSQL_DB_SOCK'};
  my $DBNAME = $ENV{'LIMESTONE_MYSQL_DB_NAME'};
  my $DBUSER = $ENV{'LIMESTONE_MYSQL_DB_USER'};
  my $DBPASS = $ENV{'LIMESTONE_MYSQL_DB_PASS'};
  print_dav_vhost_config
    (*LIMESTONE_CONFIG, $LSPORT, "mysql", $DBHOST, $DBPORT, $DBSOCK, $DBNAME, $DBUSER, $DBPASS)
}

close(LIMESTONE_CONFIG) or die("couldn't close $LIMESTONE_CONFIG");

open(ORIG_CONFIG, $ORIG_CONFIG) or die("couldn't open $ORIG_CONFIG");
open(NEWCONFIG, '>', $NEWCONFIG) or die("couldn't open $NEWCONFIG");
  

while (<ORIG_CONFIG>) {
  s/^Listen 80$/#Listen 80/;

  s|(LogFormat "%h) %l (.* combined)$|$1 %{Host}i $2|;
  s|(CustomLog "logs/access_log" common$)|#$1|;
  s|#(CustomLog "logs/access_log" combined$)|$1|;
  print NEWCONFIG;
}
print NEWCONFIG "\nInclude conf/limestone.conf\n";

close(ORIG_CONFIG) or die("couldn't close $ORIG_CONFIG");
close(NEWCONFIG) or die("couldn't close $NEWCONFIG");

rename($NEWCONFIG,$CONFIG) or
  die ("couldn't rename $NEWCONFIG to $CONFIG");

exit 0;
    
